### ISSUE TITLE
Readiness probe fails in Inbox

### ISSUE THREAD

**Issue by blankdots** [NBISweden/LocalEGA-helm#35]
### Expected Behavior
Inbox Readiness should not fail in OpenSSH inbox.

### Current Behavior
There is an error message:
```
Did not receive identification string from x.x.x.x port 56420
[MQ] Loading configuration /etc/ega/mq.conf
Did not receive identification string from x.x.x.x port 56458
[MQ] Loading configuration /etc/ega/mq.conf
Did not receive identification string from x.x.x.x port 56510
[MQ] Loading configuration /etc/ega/mq.conf
Did not receive identification string from x.x.x.x port 56552
```

### Possible Solution
```
     readinessProbe:
          exec:
            command: 
            - sh
            - -ec
            - ps -ef | grep ega-sshd
          initialDelaySeconds: 30
          periodSeconds: 15
```
or maybe it should be different depending on the inbox Mina or OpenSSH

### Steps to Reproduce

1. Start Helm charts
2. wait till inbox starts
3. kubectl logs -f -n lega lega-localega-inbox-xxxxx

### Context (Environment)
Started the Helm charts with OpenSSH inbox
